[package]
name = "ym2151"
version = "0.1.0"
edition = "2021"

[lib]
name = "ym2151"
crate-type = ["staticlib", "cdylib"]  # 静的と動的両方

[build-dependencies]
cc = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
